### ISSUE TITLE
Artificer catalogue broken

### ISSUE THREAD

**Issue by TacoTurtlecomics** [KingEnderBrine/-RoR2-LobbySkinsFix#1]
Hey, this mod is great. Unfortunately, it breaks half of the artificer skins by just not loading them in the first place, at least not in the lobby. For reference, download the Haydee artificer skin to test and see for yourself.

**Comment by KingEnderBrine** [comment]
These skins are broken by themselves, they throw errors if you select them even without `LobbySkinsFix`, but with `LobbySkinsFix` instead of throwing the error during applying the skin it does it before. But I will add checks to not break what vanilla can semi-handle.

**Comment by KingEnderBrine** [comment]
Should work now
