### ISSUE TITLE
Strange issues after updating to 1.2.1

### ISSUE THREAD

**Issue by GreatestFool** [KingEnderBrine/-RoR2-LobbySkinsFix#2]
Profile code: 0187cc1c-6605-8018-84cd-23a21deeba36

Some friends and I are getting an intermittent, if hilarious, bug when switching to and fro the [LazyHuntress](https://thunderstore.io/package/Nix/LazyHuntress/1.0.2/) and default skins. I don't know if the skin is broken in and of itself like you've mentioned some skins are in issue #1, however, there are no errors that occurs when switching. All it really does is give [you some rather fancy new pants,](https://user-images.githubusercontent.com/3003484/235292882-775ca176-a349-4944-b6b4-1acff32fc86c.jpg) and may also cause a strange case of becoming gnome sized during a run. As in literally smaller than lunar pods. I wish I took a screenshot of that. I do not have logs of this time, sadly, as it was in the middle of some playtime with my friends and we were just focused on getting a run going.

While I can no longer replicate the issue on my machine, users that connect using the modpack can occasionally get it to bug out. I can not remember if they decided to spawn in as the bugged skin, and I cannot remember another case of gnomeness at least.

We had a few more mods than the profile now has yesterday, and may have been the cause of the issue for all I know.
- [HistoryFix](https://thunderstore.io/package/6thmoon/HistoryFix/)
- [WaterTweaker](https://thunderstore.io/package/Judgy/WaterTweaker/)
- [Raise_Monster_Level_Cap](https://thunderstore.io/package/Moffein/Raise_Monster_Level_Cap/)
- [WellRoundedBalance](https://thunderstore.io/package/TheBestAssociatedLargelyLudicrousSillyheadGroup/WellRoundedBalance/) and all the mods it installs

We first had some unrelated networking issue caused by the mods, where we'd either be disconnected in the lobby or spawn outside the map without spawning in as characters properly. I know this isn't related to this mod, as mentioned, but I just wanted to mention which mods where disabled and uninstalled when, because I can't remember exactly when the issue of the lobby skin switching occurred, so it may have been some interactions with these mods that caused it. [Exchange_Changes](https://thunderstore.io/package/Flyingcomputer/Exchange_Changes/) was also disabled because WellRoundedBalance mentions it integrates the mod or its features. It's a bit unclear in my opinion, but I felt that it didn't hurt to disable it just in case.

The first to go were HistoryFix, WaterTweaker and Raise_Monster_Level_Cap. We still had some lobby disconnect issues, so WellRoundedBalance and its component mods were yeeted, and then we're almost at where my friends and I are now. We still had some spawning issues, but if I remember correctly, we did have the skin switching issue by now. At this time, [BalancedObliterateRedux](https://thunderstore.io/package/Nebby/BalancedObliterateRedux/) and [Ephemeral_Coins](https://thunderstore.io/package/VarnaScelestus/Ephemeral_Coins/) were also activated at the same time while we were debugging. BalancedObliterateRedux is now disabled, because it and Ephemeral_Coins likely are incompatible.

I know this issue body became larger than I'd hoped, but I simply wanted to provide all the information I felt is related or may be related to the lobby issue ¯\\\_(ツ)_/¯

**Comment by KingEnderBrine** [comment]
It's not because of 1.2.1. The issue is that the skin has dynamic bones (for the ears and stuff) which also requires to do stuff that `LobbySkinFix` can't reverse, because it supports only vanilla skin system. So the skin mod should do it itself when another skin is selected, but it doesn't. Nothing I can do about really.

**Comment by GreatestFool** [comment]
Reasonable, I suppose. Is it just happenstance that it happened to occur after updating this mod then? Not that I don't believe you, I'm just curious.

**Comment by KingEnderBrine** [comment]
It is indeed just a coincidence and could've happened on a previous version

**Comment by GreatestFool** [comment]
Weird. But oh well, it's not like it's game breaking anyway. Thanks for the help!
